repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy --strict . --allow-untyped-calls
        language: system
        always_run: true
        pass_filenames: false