root_dir = "."

[command]
dev = [
  "uvicorn main:app --host 0.0.0.0 --port 3000",
  # "ngrok http --url=admittedly-adequate-scorpion.ngrok-free.app 3000",
  "npm run minify",
  "npx tailwindcss -i ./web/static/input.css -o ./web/static/style.css --minify",
]
prod = []
test = []

[exclude]
dir = [
  "./.git",
  "./node_modules",
  "./__pycache__",
  "./.ruff_cache",
  "./.mypy_cache",
  "./.vscode",
  "./.venv",
]
file = []
ext = []
