root_dir = "."

[command]
dev = [
  "DEBUG=1 python3 main.py",
  "ngrok http --url=admittedly-adequate-scorpion.ngrok-free.app 3000",
  # "npm run minify",
  # "npx tailwindcss -i ./static/input.css -o ./static/style.css --minify",
]
prod = []
test = []

[exclude]
dir = [
  ".git",
  "node_modules",
  "__pycache__",
  ".ruff_cache",
  ".mypy_cache",
  ".vscode",
  ".venv",
  "dist",
]
file = []
ext = []
